/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as HIdRouteImport } from './routes/h.$id'
import { Route as KIdRouteImport } from './routes/k.$id'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HIdRoute = HIdRouteImport.update({
  id: '/h/$id',
  path: '/h/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KIdRoute = KIdRouteImport.update({
  id: '/k/$id',
  path: '/k/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/c/$id': typeof CIdRoute
  '/h/$id': typeof HIdRoute
  '/k/$id': typeof KIdRoute
  '/r/$id': typeof RIdRoute
  '/t/$id': typeof TIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/c/$id': typeof CIdRoute
  '/h/$id': typeof HIdRoute
  '/k/$id': typeof KIdRoute
  '/r/$id': typeof RIdRoute
  '/t/$id': typeof TIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/c/$id': typeof CIdRoute
  '/h/$id': typeof HIdRoute
  '/k/$id': typeof KIdRoute
  '/r/$id': typeof RIdRoute
  '/t/$id': typeof TIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/c/$id'
    | '/h/$id'
    | '/k/$id'
    | '/r/$id'
    | '/t/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/c/$id'
    | '/h/$id'
    | '/k/$id'
    | '/r/$id'
    | '/t/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/c/$id'
    | '/h/$id'
    | '/k/$id'
    | '/r/$id'
    | '/t/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CIdRoute: typeof CIdRoute
  HIdRoute: typeof HIdRoute
  KIdRoute: typeof KIdRoute
  RIdRoute: typeof RIdRoute
  TIdRoute: typeof TIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$id': {
      id: '/h/$id'
      path: '/h/$id'
      fullPath: '/h/$id'
      preLoaderRoute: typeof HIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$id': {
      id: '/k/$id'
      path: '/k/$id'
      fullPath: '/k/$id'
      preLoaderRoute: typeof KIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CIdRoute: CIdRoute,
  HIdRoute: HIdRoute,
  KIdRoute: KIdRoute,
  RIdRoute: RIdRoute,
  TIdRoute: TIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
